In [1]:
import pandas as pd

# Read a .csv from a URL with Pandas

Target website: https://www.football-data.co.uk/data.php

In [3]:
# reading 1 csv file from the website
df_premier21 = pd.read_csv('https://www.football-data.co.uk/mmz4281/2122/E0.csv')

In [4]:
# showing dataframe
df_premier21

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,E0,13/08/2021,20:00,Brentford,Arsenal,2,0,H,1,0,...,1.62,0.50,1.75,2.05,1.81,2.13,2.05,2.17,1.80,2.09
1,E0,14/08/2021,12:30,Man United,Leeds,5,1,H,1,0,...,2.25,-1.00,2.05,1.75,2.17,1.77,2.19,1.93,2.10,1.79
2,E0,14/08/2021,15:00,Burnley,Brighton,1,2,A,1,0,...,1.62,0.25,1.79,2.15,1.81,2.14,1.82,2.19,1.79,2.12
3,E0,14/08/2021,15:00,Chelsea,Crystal Palace,3,0,H,2,0,...,1.94,-1.50,2.05,1.75,2.12,1.81,2.16,1.93,2.06,1.82
4,E0,14/08/2021,15:00,Everton,Southampton,3,1,H,0,1,...,1.67,-0.50,2.05,1.88,2.05,1.88,2.08,1.90,2.03,1.86
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,E0,22/05/2022,16:00,Crystal Palace,Man United,1,0,H,1,0,...,2.04,0.25,1.68,2.15,1.74,2.23,1.88,2.25,1.74,2.16
376,E0,22/05/2022,16:00,Leicester,Southampton,4,1,H,0,0,...,2.63,-0.75,1.83,2.07,1.88,2.03,1.94,2.26,1.87,2.01
377,E0,22/05/2022,16:00,Liverpool,Wolves,3,1,H,1,1,...,3.28,-2.50,2.02,1.77,2.06,1.83,2.19,1.99,2.07,1.80
378,E0,22/05/2022,16:00,Man City,Aston Villa,3,2,H,0,1,...,3.36,-2.25,2.06,1.84,2.05,1.86,2.09,2.03,2.01,1.87
379,E0,22/05/2022,16:00,Norwich,Tottenham,0,5,A,0,2,...,2.40,1.50,1.95,1.95,1.96,1.94,2.16,1.98,1.99,1.89

In [5]:
# rename columns
df_premier21 = df_premier21.rename(columns={'Date':'date',
                                            'HomeTeam':'home_team',
                                            'AwayTeam':'away_team',
                                            'FTHG':'home_goals',
                                            'FTAG':'away_goals'})

In [6]:
# show dataframe
df_premier21

,Div,date,Time,home_team,away_team,home_goals,away_goals,FTR,HTHG,HTAG,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,E0,13/08/2021,20:00,Brentford,Arsenal,2,0,H,1,0,...,1.62,0.50,1.75,2.05,1.81,2.13,2.05,2.17,1.80,2.09
1,E0,14/08/2021,12:30,Man United,Leeds,5,1,H,1,0,...,2.25,-1.00,2.05,1.75,2.17,1.77,2.19,1.93,2.10,1.79
2,E0,14/08/2021,15:00,Burnley,Brighton,1,2,A,1,0,...,1.62,0.25,1.79,2.15,1.81,2.14,1.82,2.19,1.79,2.12
3,E0,14/08/2021,15:00,Chelsea,Crystal Palace,3,0,H,2,0,...,1.94,-1.50,2.05,1.75,2.12,1.81,2.16,1.93,2.06,1.82
4,E0,14/08/2021,15:00,Everton,Southampton,3,1,H,0,1,...,1.67,-0.50,2.05,1.88,2.05,1.88,2.08,1.90,2.03,1.86
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,E0,22/05/2022,16:00,Crystal Palace,Man United,1,0,H,1,0,...,2.04,0.25,1.68,2.15,1.74,2.23,1.88,2.25,1.74,2.16
376,E0,22/05/2022,16:00,Leicester,Southampton,4,1,H,0,0,...,2.63,-0.75,1.83,2.07,1.88,2.03,1.94,2.26,1.87,2.01
377,E0,22/05/2022,16:00,Liverpool,Wolves,3,1,H,1,1,...,3.28,-2.50,2.02,1.77,2.06,1.83,2.19,1.99,2.07,1.80
378,E0,22/05/2022,16:00,Man City,Aston Villa,3,2,H,0,1,...,3.36,-2.25,2.06,1.84,2.05,1.86,2.09,2.03,2.01,1.87
379,E0,22/05/2022,16:00,Norwich,Tottenham,0,5,A,0,2,...,2.40,1.50,1.95,1.95,1.96,1.94,2.16,1.98,1.99,1.89

# Read .csv from Multiple URLs with Pandas
https://www.football-data.co.uk/mmz4281/2122/E0.csv

<b> Link: root + season + league </b>

In [7]:
# link structure
"https://www.football-data.co.uk/mmz4281/" + "2122" + "/" + "E0" + ".csv"

'https://www.football-data.co.uk/mmz4281/2122/E0.csv'

In [8]:
# create a root variable
root = "https://www.football-data.co.uk/mmz4281/"

## Multiple leagues

- https://www.football-data.co.uk/mmz4281/2122/E0.csv
- https://www.football-data.co.uk/mmz4281/2122/E1.csv
- https://www.football-data.co.uk/mmz4281/2122/E2.csv
- https://www.football-data.co.uk/mmz4281/2122/E3.csv
- https://www.football-data.co.uk/mmz4281/2122/EC.csv

In [32]:
# creating list of leagues
leagues = ['E0','E1','E2','E3','EC']
frames = []

# looping through leagues, read multiple csv and append it into a list
for league in leagues:
    df = pd.read_csv( root + "2122" + "/" + league + ".csv", encoding='unicode_escape' )
    frames.append(df)

In [33]:
# length of frames
len(frames)

5

In [34]:
# show 1st, 2nd and 3rd element
frames[0]

,ï»¿Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,E0,13/08/2021,20:00,Brentford,Arsenal,2,0,H,1,0,...,1.62,0.50,1.75,2.05,1.81,2.13,2.05,2.17,1.80,2.09
1,E0,14/08/2021,12:30,Man United,Leeds,5,1,H,1,0,...,2.25,-1.00,2.05,1.75,2.17,1.77,2.19,1.93,2.10,1.79
2,E0,14/08/2021,15:00,Burnley,Brighton,1,2,A,1,0,...,1.62,0.25,1.79,2.15,1.81,2.14,1.82,2.19,1.79,2.12
3,E0,14/08/2021,15:00,Chelsea,Crystal Palace,3,0,H,2,0,...,1.94,-1.50,2.05,1.75,2.12,1.81,2.16,1.93,2.06,1.82
4,E0,14/08/2021,15:00,Everton,Southampton,3,1,H,0,1,...,1.67,-0.50,2.05,1.88,2.05,1.88,2.08,1.90,2.03,1.86
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,E0,22/05/2022,16:00,Crystal Palace,Man United,1,0,H,1,0,...,2.04,0.25,1.68,2.15,1.74,2.23,1.88,2.25,1.74,2.16
376,E0,22/05/2022,16:00,Leicester,Southampton,4,1,H,0,0,...,2.63,-0.75,1.83,2.07,1.88,2.03,1.94,2.26,1.87,2.01
377,E0,22/05/2022,16:00,Liverpool,Wolves,3,1,H,1,1,...,3.28,-2.50,2.02,1.77,2.06,1.83,2.19,1.99,2.07,1.80
378,E0,22/05/2022,16:00,Man City,Aston Villa,3,2,H,0,1,...,3.36,-2.25,2.06,1.84,2.05,1.86,2.09,2.03,2.01,1.87
379,E0,22/05/2022,16:00,Norwich,Tottenham,0,5,A,0,2,...,2.40,1.50,1.95,1.95,1.96,1.94,2.16,1.98,1.99,1.89

## Multiple Seasons

In [36]:
for season in range(15,21):
    print(str(season) + str(season+1))

1516
1617
1718
1819
1920
2021

In [37]:
leagues = ['E0','E2', 'E3']

frames = []

# loop through range of seasons and insert new column
for league in leagues:
    for season in range(15,21): # range of seasons
        df = pd.read_csv(root + str(season) + str(season+1) + "/" + league + ".csv")
#         df['season'] = season
        df.insert(1, 'season', season)
        frames.append(df)

In [38]:
#total frames (6 seasons * 3 leagues)
len(frames)

18

In [39]:
#show 1st and last element
frames[0]

,Div,season,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,BbAv<2.5,BbAH,BbAHh,BbMxAHH,BbAvAHH,BbMxAHA,BbAvAHA,PSCH,PSCD,PSCA
0,E0,15,08/08/2015,Bournemouth,Aston Villa,0,1,A,0,0,...,1.79,26,-0.50,1.98,1.93,1.99,1.92,1.82,3.88,4.70
1,E0,15,08/08/2015,Chelsea,Swansea,2,2,D,2,1,...,1.99,27,-1.50,2.24,2.16,1.80,1.73,1.37,5.04,10.88
2,E0,15,08/08/2015,Everton,Watford,2,2,D,0,1,...,1.96,26,-1.00,2.28,2.18,1.76,1.71,1.75,3.76,5.44
3,E0,15,08/08/2015,Leicester,Sunderland,4,2,H,3,0,...,1.67,26,-0.50,2.00,1.95,1.96,1.90,1.79,3.74,5.10
4,E0,15,08/08/2015,Man United,Tottenham,1,0,H,1,0,...,2.01,26,-1.00,2.20,2.09,1.82,1.78,1.64,4.07,6.04
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,E0,15,15/05/2016,Stoke,West Ham,2,1,H,0,1,...,2.27,30,0.25,2.11,2.03,1.87,1.83,3.05,4.00,2.26
376,E0,15,15/05/2016,Swansea,Man City,1,1,D,1,1,...,2.45,31,1.00,2.14,2.05,1.85,1.81,7.05,5.00,1.47
377,E0,15,15/05/2016,Watford,Sunderland,2,2,D,0,1,...,2.10,29,-0.50,2.06,2.01,1.91,1.85,1.64,4.52,5.27
378,E0,15,15/05/2016,West Brom,Liverpool,1,1,D,1,1,...,2.09,30,-0.25,2.10,2.05,1.86,1.81,2.61,3.75,2.70
379,E0,15,17/05/2016,Man United,Bournemouth,3,1,H,1,0,...,2.20,29,-0.75,1.88,1.84,2.08,2.02,1.50,4.60,7.03

# Organize All the Data in a Dictionary

In [40]:
# create a dictionary with original name of league as key
dict_countries = {
              'Spanish La Liga':'SP1', 'Spanish Segunda Division':'SP2',
              'German Bundesliga':'D1', 
              'English Premier League':'E0', 'English League 1':'E2', 'English League 2':'E3',
             }

In [41]:
#get a dictionary element
dict_countries['German Bundesliga']

'D1'

In [43]:
dict_historical_data = {} 

# looping through key elements
for league in dict_countries:
    frames = [] # one dataframe per league
    for season in range(15, 21):
        df = pd.read_csv(root + str(season) + str(season+1) + "/" + dict_countries[league]+ ".csv")
        df.insert(1, 'season', season)
        frames.append(df)
    df_frames = pd.concat(frames) # storing all seasons of a league in a single dataframe
    dict_historical_data[league] = df_frames # assigning dataframe to a new dictionary

In [44]:
#show dataframe inside disct_historical_data
dict_historical_data['Spanish La Liga']

,Div,season,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,SP1,15,21/08/15,Malaga,Sevilla,0,0,D,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,SP1,15,22/08/15,Ath Madrid,Las Palmas,1,0,H,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,SP1,15,22/08/15,Espanol,Getafe,1,0,H,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,SP1,15,22/08/15,La Coruna,Sociedad,0,0,D,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,SP1,15,22/08/15,Vallecano,Valencia,0,0,D,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,SP1,20,22/05/2021,Osasuna,Sociedad,0,1,A,0,0,...,2.34,1.00,2.07,1.86,2.06,1.87,2.07,1.96,1.98,1.88
376,SP1,20,22/05/2021,Real Madrid,Villarreal,2,1,H,0,1,...,2.57,-1.00,2.01,1.92,2.00,1.93,2.02,2.02,1.95,1.92
377,SP1,20,22/05/2021,Valladolid,Ath Madrid,1,2,A,1,0,...,2.30,1.50,1.90,2.03,1.90,2.02,1.95,2.06,1.90,1.97
378,SP1,20,23/05/2021,Granada,Getafe,0,0,D,0,0,...,1.80,0.25,1.73,2.08,1.77,2.18,1.84,2.23,1.77,2.12
379,SP1,20,23/05/2021,Sevilla,Alaves,1,0,H,0,0,...,2.40,-1.50,1.97,1.96,1.93,1.99,2.13,2.03,1.99,1.88